Repository UBC-MDS/DSCI522-2425-22-wine-chromatic-profile, pull requests merged in 2024-12, with the labels that each got.

#29 data download and clean scripts
  scripts/clean_data.py
  scripts/download.py
  scripts/test.py
Labels: enhancement

#32 Preprocessing script
  preprocessing.py
Labels: enhancement

#35 Bug fixes in script
  scripts/clean_data.py
  scripts/clean_n_split_data.py
  scripts/model_evaluation_wine_predictor.py
  scripts/preprocessing.py
Labels: fix

#36 finished eda and validation before modeling
  scripts/eda_n_correlation_check.py
  scripts/validation_before_split.py
Labels: refactor

#37 Updated click command to split table and figure path
  scripts/eda_n_correlation_check.py
Labels: refactor

#39 fixed script formats and validation after modeling
  scripts/clean_data.py
  scripts/clean_n_split_data.py
  scripts/download.py
  scripts/eda_n_correlation_check.py
  scripts/model_evaluation_wine_predictor.py
  scripts/validation_before_split.py
Labels: enhancement, fix

#41 added empty row check
  scripts/validation_before_split.py
Labels: refactor

#42 Quarto dependency
  Dockerfile
  README.md
  analysis/analysis.html
  analysis/analysis.ipynb
  conda-linux-64.lock
  conda-osx-64.lock
  conda-osx-arm64.lock
  conda-win-64.lock
  data/wine_ex.csv
  data/wine_test.csv
  data/wine_train.csv
  docker-compose.yml
  docs/index.html
  environment.yaml
  index.html
  report/.ipynb_checkpoints/.analysis-checkpoint.html.icloud
  report/.ipynb_checkpoints/.analysis-checkpoint.ipynb.icloud
  report/.ipynb_checkpoints/report-checkpoint.pdf
  report/.ipynb_checkpoints/report-checkpoint.qmd
  report/references.bib
  report/report.html
  report/report.pdf
  report/report.qmd
  results/figures/confusion_matrix.png
  results/figures/feature_correlation.png
  results/figures/feature_densities_by_class.png
  results/figures/pr_curve.png
  results/models/wine_pipeline.pickle
  results/models/wine_random_search.pickle
  results/tables/cross_validation.csv
  results/tables/drift_score.csv
  results/tables/feature_datatypes.csv
  results/tables/random_search.csv
  results/tables/summary_statistics.csv
  results/tables/test_scores.csv
  scripts/clean_data.py
  scripts/clean_n_split_data.py
  scripts/download.py
  scripts/eda_n_correlation_check.py
  scripts/model_evaluation_wine_predictor.py
  scripts/preprocessing.py
  scripts/test.py
  scripts/validation_before_split.py
Labels: enhancement

#46 added click dependency and README update
  README.md
  conda-linux-64.lock
  data/wine_ex.csv
  environment.yaml
  report/.ipynb_checkpoints/.analysis-checkpoint.html.icloud
  report/.ipynb_checkpoints/.analysis-checkpoint.ipynb.icloud
Labels: documentation, enhancement

#49 html and pdf reports added
  docs/index.html
  report/report.html
  report/report.pdf
Labels: fix

#60 test script for data splitting
  scripts/clean_n_split_data.py
  src/__init__.py
  src/split_data.py
  tests/train_test_split_test.py
Labels: enhancement

#65 Milestone 2 fix
  .gitignore
  Dockerfile
  README.md
  docker-compose.yml
  docs/report.pdf
  report/.report.html.icloud
  report/report.pdf
  results/models/wine_random_search.pickle
  results/tables/random_search.csv
  tests/README
Labels: enhancement

#68 peer review fix
  report/report.qmd
Labels: fix

#69 evaluation function script + test
  scripts/model_evaluation_wine_predictor.py
  src/evaluation.py
  tests/.ipynb_checkpoints/README-checkpoint
  tests/README
  tests/test_evaluation.py
Labels: documentation, enhancement, fix

#70 changelog added
  CHANGELOG.md
Labels: documentation

#72 Ms1 fixes
  .gitignore
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  docs/index.html
  docs/report.pdf
  docs/report.qmd
  report/report.html
  report/report.pdf
  report/report.qmd
  results/models/wine_random_search.pickle
  results/tables/random_search.csv
  scripts/.ipynb_checkpoints/model_evaluation_wine_predictor-checkpoint.py
  scripts/model_evaluation_wine_predictor.py
  tests/.ipynb_checkpoints/README-checkpoint
  tests/README
  wine.csv
Labels: documentation, enhancement, fix

#73 Update README.md
  README.md
Labels: documentation
