Repository UBC-MDS/DSCI522-2425-22-wine-chromatic-profile, pull requests merged in 2024-11, with the labels that each got.

#4 test v1
  Dockerfile
  analysis/analysis.ipynb
  conda-linux-64.lock
  conda-lock.yml
  conda-osx-64.lock
  conda-osx-arm64.lock
  conda-win-64.lock
  docker-compose.yml
  environment.yaml
Labels: enhancement

#5 GitHub actions
  .github/workflows/docker-publish.yml
  Dockerfile
  README.md
  analysis/analysis.ipynb
  docker-compose.yml
  requirements.txt
Labels: enhancement

#7 Finished validation 1-4 and stored in a different notebook under /analysis
  analysis/validation1-4.ipynb
Labels: enhancement

#10 Valid1 4
  analysis/analysis.ipynb
Labels: enhancement

#11 updated readme with docker instructions
  README.md
  img/docker_instructions.png
Labels: documentation, enhancement

#16 github pages report updated
  analysis/analysis.html
  analysis/analysis.ipynb
  index.html
Labels: fix
